/* ==================================================
   1. タイムラインデータ取得
================================================== */
function getTimelineItems() {

    const items = loadData(
        STORAGE_KEYS.timelines,
        []
    );

    return Array.isArray(items)
        ? items
        : [];

}

/* ==================================================
   2. タイムライン保存
================================================== */
function saveTimelineItems(items) {

    return saveData(
        STORAGE_KEYS.timelines,
        Array.isArray(items)
            ? items
            : []
    );

}

/* ==================================================
   3. 選択中ライブのタイムライン
================================================== */
function getSelectedLiveTimeline() {

    const selectedLiveId =
        getSelectedLiveId();

    if (!selectedLiveId) {
        return [];
    }

    return getTimelineItems()
        .filter(
            item =>
                String(item.liveId) ===
                String(selectedLiveId)
        )
        .sort(
            (a, b) =>
                String(a.time).localeCompare(
                    String(b.time)
                )
        );

}

/* ==================================================
   4. フォーム要素
================================================== */
function getTimelineFormElements() {

    return {
        form:
            document.getElementById(
                "timelineForm"
            ),
        editingId:
            document.getElementById(
                "editingTimelineId"
            ),
        time:
            document.getElementById(
                "timelineTime"
            ),
        title:
            document.getElementById(
                "timelineTitle"
            ),
        memo:
            document.getElementById(
                "timelineMemo"
            )
    };

}

/* ==================================================
   5. フォーム初期化
================================================== */
function resetTimelineForm() {

    const elements =
        getTimelineFormElements();

    if (!elements.form) {
        return;
    }

    elements.form.reset();

    if (elements.editingId) {
        elements.editingId.value = "";
    }

    clearFormErrors(
        elements.form
    );

    const submitButton =
        elements.form.querySelector(
            'button[type="submit"]'
        );

    if (submitButton) {

        submitButton.innerHTML = `
            <i class="fa-solid fa-plus"></i>
            追加
        `;

    }

}

/* ==================================================
   6. 自動予定同期
================================================== */
function syncAutomaticTimelineItems() {

    const selectedLive =
        getSelectedLive();

    if (!selectedLive?.id) {
        return;
    }

    const allItems =
        getTimelineItems();

    let changed = false;

    const autoItems = [
        {
            title: "開場",
            time:
                selectedLive.openTime,
            memo:
                "ライブ登録情報から自動反映"
        },
        {
            title: "開演",
            time:
                selectedLive.startTime,
            memo:
                "ライブ登録情報から自動反映"
        }
    ];

    autoItems.forEach(
        autoItem => {

            if (!autoItem.time) {
                return;
            }

            const existingIndex =
                allItems.findIndex(
                    item =>
                        String(item.liveId) ===
                            String(selectedLive.id) &&
                        item.title ===
                            autoItem.title &&
                        item.autoGenerated ===
                            true
                );

            if (existingIndex >= 0) {

                if (
                    allItems[
                        existingIndex
                    ].time !==
                    autoItem.time
                ) {

                    allItems[
                        existingIndex
                    ] = {
                        ...allItems[
                            existingIndex
                        ],
                        time:
                            autoItem.time,
                        memo:
                            autoItem.memo,
                        updatedAt:
                            new Date()
                                .toISOString()
                    };

                    changed = true;

                }

            } else {

                allItems.push({
                    id:
                        generateId(
                            "timeline"
                        ),
                    liveId:
                        selectedLive.id,
                    time:
                        autoItem.time,
                    title:
                        autoItem.title,
                    memo:
                        autoItem.memo,
                    autoGenerated:
                        true,
                    createdAt:
                        new Date()
                            .toISOString(),
                    updatedAt:
                        new Date()
                            .toISOString()
                });

                changed = true;

            }

        }
    );

    if (changed) {

        saveTimelineItems(
            allItems
        );

    }

}

/* ==================================================
   7. 入力検証
================================================== */
function validateTimelineForm() {

    const elements =
        getTimelineFormElements();

    return validateRequiredFields([
        {
            input:
                elements.time,
            label:
                "時間"
        },
        {
            input:
                elements.title,
            label:
                "予定"
        }
    ]);

}

/* ==================================================
   8. 予定保存
================================================== */
function handleTimelineSubmit(
    event
) {

    event.preventDefault();

    const selectedLive =
        getSelectedLive();

    if (!selectedLive) {

        showToast(
            "先にライブを登録してください。",
            "warning"
        );

        showPage("home");

        return;

    }

    if (!validateTimelineForm()) {

        showToast(
            "入力内容を確認してください。",
            "error"
        );

        return;

    }

    const elements =
        getTimelineFormElements();

    const editingId =
        elements.editingId?.value ||
        "";

    const allItems =
        getTimelineItems();

    const existingItem =
        allItems.find(
            item =>
                String(item.id) ===
                String(editingId)
        );

    const timelineData = {
        id:
            editingId ||
            generateId(
                "timeline"
            ),
        liveId:
            selectedLive.id,
        time:
            elements.time.value,
        title:
            elements.title.value.trim(),
        memo:
            elements.memo.value.trim(),
        autoGenerated:
            existingItem
                ?.autoGenerated ||
            false,
        createdAt:
            existingItem
                ?.createdAt ||
            new Date()
                .toISOString(),
        updatedAt:
            new Date()
                .toISOString()
    };

    let updatedItems;

    if (editingId) {

        updatedItems =
            allItems.map(
                item => {

                    if (
                        String(item.id) ===
                        String(editingId)
                    ) {

                        return timelineData;

                    }

                    return item;

                }
            );

    } else {

        updatedItems = [
            ...allItems,
            timelineData
        ];

    }

    saveTimelineItems(
        updatedItems
    );

    resetTimelineForm();

    renderTimeline();

    showToast(
        editingId
            ? "予定を更新しました。"
            : "予定を追加しました。",
        "success"
    );

}

/* ==================================================
   9. 編集開始
================================================== */
function startEditTimeline(
    timelineId
) {

    const item =
        getTimelineItems()
            .find(
                data =>
                    String(data.id) ===
                    String(timelineId)
            );

    if (!item) {

        showToast(
            "予定が見つかりません。",
            "error"
        );

        return;

    }

    const elements =
        getTimelineFormElements();

    elements.editingId.value =
        item.id;

    elements.time.value =
        item.time || "";

    elements.title.value =
        item.title || "";

    elements.memo.value =
        item.memo || "";

    const submitButton =
        elements.form?.querySelector(
            'button[type="submit"]'
        );

    if (submitButton) {

        submitButton.innerHTML = `
            <i class="fa-regular fa-floppy-disk"></i>
            更新
        `;

    }

    elements.form?.scrollIntoView({
        behavior: "smooth",
        block: "center"
    });

    elements.title?.focus();

    showToast(
        "予定を編集できます。"
    );

}

/* ==================================================
   10. 削除
================================================== */
function requestDeleteTimeline(
    timelineId
) {

    const item =
        getTimelineItems()
            .find(
                data =>
                    String(data.id) ===
                    String(timelineId)
            );

    if (!item) {
        return;
    }

    openConfirmModal({
        title:
            "予定を削除",
        message:
            `「${item.time} ${item.title}」を削除しますか？`,
        confirmText:
            "削除する",
        onConfirm: () => {

            deleteTimeline(
                timelineId
            );

        }
    });

}

function deleteTimeline(
    timelineId
) {

    const updatedItems =
        getTimelineItems()
            .filter(
                item =>
                    String(item.id) !==
                    String(timelineId)
            );

    saveTimelineItems(
        updatedItems
    );

    renderTimeline();

    showToast(
        "予定を削除しました。",
        "success"
    );

}

/* ==================================================
   11. タイムラインHTML
================================================== */
function createTimelineItemHtml(
    item
) {

    const autoBadge =
        item.autoGenerated
            ? `
                <span class="timeline-auto-badge">
                    自動反映
                </span>
            `
            : "";

    return `
        <article
            class="timeline-item"
            data-timeline-id="${escapeHtml(item.id)}"
        >

            <time class="timeline-time">
                ${escapeHtml(item.time || "--:--")}
            </time>

            <div class="timeline-card">

                <div class="timeline-title-row">

                    <h3>
                        ${escapeHtml(item.title)}
                    </h3>

                    ${autoBadge}

                </div>

                ${
                    item.memo
                        ? `
                            <p>
                                ${escapeHtml(item.memo)}
                            </p>
                        `
                        : ""
                }

            </div>

            <div class="timeline-item-actions">

                <button
                    type="button"
                    class="timeline-action-button edit-timeline-button"
                    data-timeline-id="${escapeHtml(item.id)}"
                    aria-label="${escapeHtml(item.title)}を編集"
                    title="編集"
                >
                    <i class="fa-regular fa-pen-to-square"></i>
                </button>

                <button
                    type="button"
                    class="timeline-action-button delete delete-timeline-button"
                    data-timeline-id="${escapeHtml(item.id)}"
                    aria-label="${escapeHtml(item.title)}を削除"
                    title="削除"
                >
                    <i class="fa-regular fa-trash-can"></i>
                </button>

            </div>

        </article>
    `;

}

/* ==================================================
   12. タイムライン表示
================================================== */
function renderTimeline() {

    const container =
        document.getElementById(
            "timelineList"
        );

    if (!container) {
        return;
    }

    const selectedLive =
        getSelectedLive();

    if (!selectedLive) {

        container.innerHTML = `
            <div class="empty-message">
                ライブを登録すると、開場・開演時間が自動で反映されます。
            </div>
        `;

        return;

    }

    syncAutomaticTimelineItems();

    const items =
        getSelectedLiveTimeline();

    if (items.length === 0) {

        container.innerHTML = `
            <div class="empty-message">
                予定が登録されていません。
            </div>
        `;

        return;

    }

    container.innerHTML =
        items
            .map(
                createTimelineItemHtml
            )
            .join("");

}

/* ==================================================
   13. Vlog撮影ガイド更新
================================================== */
function updateVlogGuideFromTimeline() {

    const guideElement =
        document.getElementById(
            "vlogGuideText"
        );

    if (!guideElement) {
        return;
    }

    const timeline =
        getSelectedLiveTimeline();

    if (timeline.length === 0) {

        guideElement.textContent =
            "タイムスケジュールを登録すると、おすすめの撮影シーンを表示します。";

        return;

    }

    const nowTime =
        new Intl.DateTimeFormat(
            "ja-JP",
            {
                hour: "2-digit",
                minute: "2-digit",
                hour12: false
            }
        ).format(
            new Date()
        );

    const nextItem =
        timeline.find(
            item =>
                item.time >=
                nowTime
        ) || timeline[0];

    const suggestion =
        getVlogSuggestion(
            nextItem.title
        );

    guideElement.textContent =
        `【${nextItem.time} ${nextItem.title}】${suggestion}`;

}

function getVlogSuggestion(title) {

    const normalized =
        String(title)
            .toLowerCase();

    if (
        normalized.includes("出発") ||
        normalized.includes("移動")
    ) {

        return (
            "出発時の様子や電車・新幹線の車窓、駅弁などを撮影してみましょう。"
        );

    }

    if (
        normalized.includes("会場") ||
        normalized.includes("到着")
    ) {

        return (
            "会場の外観、看板、周辺のファンの様子を撮影するのがおすすめです。"
        );

    }

    if (
        normalized.includes("グッズ") ||
        normalized.includes("物販")
    ) {

        return (
            "購入したグッズやショッパー、物販会場の雰囲気を撮影してみましょう。"
        );

    }

    if (
        normalized.includes("開場")
    ) {

        return (
            "入場口やチケット、座席へ向かう前のワクワク感を残しましょう。"
        );

    }

    if (
        normalized.includes("開演")
    ) {

        return (
            "開演前の会場の雰囲気を、撮影可能な範囲で記録しましょう。"
        );

    }

    if (
        normalized.includes("終演") ||
        normalized.includes("帰宅")
    ) {

        return (
            "ライブ直後の感想や戦利品、帰り道の余韻を撮影してみましょう。"
        );

    }

    return (
        "この予定に合わせて、当日の雰囲気が伝わる短い動画を撮影してみましょう。"
    );

}

/* ==================================================
   14. 一覧操作
================================================== */
function handleTimelineListClick(
    event
) {

    const editButton =
        event.target.closest(
            ".edit-timeline-button"
        );

    const deleteButton =
        event.target.closest(
            ".delete-timeline-button"
        );

    if (editButton) {

        startEditTimeline(
            editButton.dataset
                .timelineId
        );

        return;

    }

    if (deleteButton) {

        requestDeleteTimeline(
            deleteButton.dataset
                .timelineId
        );

    }

}

/* ==================================================
   15. イベント登録
================================================== */
function initializeTimelineEvents() {

    const elements =
        getTimelineFormElements();

    if (elements.form) {

        elements.form.addEventListener(
            "submit",
            handleTimelineSubmit
        );

    }

    const container =
        document.getElementById(
            "timelineList"
        );

    if (container) {

        container.addEventListener(
            "click",
            handleTimelineListClick
        );

    }

    document.addEventListener(
        "livemate:selectedlivechange",
        () => {

            resetTimelineForm();

            renderTimeline();

            updateVlogGuideFromTimeline();

        }
    );

    document.addEventListener(
        "livemate:pagechange",
        event => {

            if (
                event.detail?.page ===
                "timeline"
            ) {

                renderTimeline();

            }

            if (
                event.detail?.page ===
                "vlog"
            ) {

                updateVlogGuideFromTimeline();

            }

        }
    );

}

/* ==================================================
   16. 初期化
================================================== */
function initializeTimelineModule() {

    initializeTimelineEvents();

    renderTimeline();

    updateVlogGuideFromTimeline();

}

/* ==================================================
   17. DOM読み込み後
================================================== */
document.addEventListener(
    "DOMContentLoaded",
    initializeTimelineModule
);